In [52]:
# Import TensorFlow
import tensorflow as tf
import numpy as np
import tensorflow_probability as tfp
print(tf.__version__)

2.5.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10]);
vector

vector.ndim

1

In [5]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

matrix.ndim

2

In [6]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter
                                                           # Higher the precision(32, 16, etc) the more precise
                                                           # the number is stored on computer, but more space.
another_matrix                                                          

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [7]:
# What's the number of dimensions
another_matrix.ndim

2

In [8]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [9]:
tensor.ndim

3

### tf.Variable


In [10]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [11]:
# Change an element in changeable_tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# How about trying .assing()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

Creating random tensors
--Used mainly for intializing the random weights and biases

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(34223)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1==random_2

Shuffling order in a tensor

--Shuffle the dataset(500 inputs were flowers, the last 500 were toys)

In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([[10, 7], 
                           [3, 4], 
                           [2, 5]])
not_shuffled.ndim
# Shuffled our non-shuffled tensor
tf.random.shuffle(not_shuffled, seed=42) # Shuffles only the array, rather than the stuff in each array

In [ ]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed = 42) # operation level random seed
# If we want our hsuffled tensors to be in the same order, 
# we've go to use the global level random seed--reproducible.

OTHER WAYS TO CREATE TENSORS

In [ ]:
# Create a tensor of all ones
tf.ones([10, 7])

In [ ]:
# Create a tensor of all zeroes
tf.zeros([3, 4])

Turn Numpy arrays into tensors

The main difference between Numpy arrays and TF tensors is that tensors can be run on a GPU for computing.

In [ ]:
# You can turn Numpy arrays into tensors
numpy_A = np.arange(1, 25, dtype=np.int32) # create Numpy array with numbers between 1 and 25-1=24
numpy_A


In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4)) # TF turns the numpy array into a TF tensor
                                          # even if you change the shape
B = tf.constant(numpy_A)
A, B
# Have to remember that the numpy_A has only 24 numbers, so the shape in the first
# line has to multiply to 24(or the size of numpy_A)
A.ndim

Getting information from Tensors

Shape: tensor.shape
Rank: tensor.ndim
Axis or Dimension: tensor[0], tensor[:, 1], etc
                              # The ":" means everything in that dimension
Size: tf.size(tensor)                              

In [ ]:
# Create a Rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5]); # 4 dimesions
                                              # 2 major groups of 3 groups of 4 x 5 arrays
print(rank_4_tensor[0]) # Getting only the first major group
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# Get various attributes or out tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0]) # to get last index, in python can just do -1
print("Total number of elements in tensor:", tf.size(rank_4_tensor).numpy()) # .numpy() doesn't give all the other bullshit

Indexing tensors

In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2] # first two elements of some_list

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :] # rank_4_tensor[:1, :1, :1, :] = rank_4_tensor[:1, :1, :1]
                             # : means everything in that dimension

In [ ]:
# Create a rank 2 tensor (2 dimension)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
# Get the last item of each row of our rank 2 tensor
print(rank_2_tensor[:, -1]) # The last two of every tensor is the row then column
print(rank_2_tensor[:2]) # When you have :2, it means to get every thing up to and including the 2 row.
print(rank_2_tensor[:, 1]) # Gets the second element of each row 

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # ... means every dimension up to a new one
                                               # ... basically is this rank_2_tensor = [:, :, tf.newaxis]
rank_3_tensor

In [ ]:
# Althernative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means to expand on the last axis


In [ ]:
# Expand on the 0-axis
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis(the row dimension)

Manipulating tensors(tensor operations)

BASIC Operations

In [ ]:
# Add values to a tensor using the addition operator
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10 # Adds ten to each of the elements, but it doesn't change tensor
tensor += 10 # THis does change the tensor 

# Multiplication also works
tensor *= 2
tensor

# Subtraction works the exact same way

In [ ]:
# We can use the tf built-in function too
tf.multiply(tensor, 2) # Doesn't change tensor
tf.add(tensor, 1)
tf.subtract(tensor, 1)
tf.divide(tensor, 1)
# ALWAYS USE THE TF FUNCTION BECAUSE THEY MAKE THINGS FASTER AND EASIER

In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant([1, 2, 3])
tf.multiply(x, y)

**Matrix Multiplication**

Rules:
1. The inner dimensions must match
2. The resulting matrix has the shape of the inner dimensions
3. The number of columns of the first tensor has to equal the number of rows of the second tensor

In [ ]:
# Matrix mul in tf
tensor = tf.constant([[10, 7], 
                     [3, 4]])
print(tensor)
tf.matmul(tensor, tensor)
# This is different from tensor * tensor OR tf.multiply(tensor, tensor)

In [ ]:
# Matmul with python character '@'
tensor @ tensor # same as tf.matmul(tensor, tensor)

In [22]:
# Create a tensor of (3, 2)
x = tf.constant([[1, 2], 
                 [3, 4],
                 [5, 6]])
y = tf.constant([[7, 8], 
                 [9, 10],
                 [11, 12]])
# Try to matmul tensors of same shape(not square)
tf.matmul(x, y)

InvalidArgumentError: ignored

In [18]:
# Let's change the shape of y
tf.reshape(y, shape=(2, 3)) # Doesn't change y
tf.matmul(x, tf.reshape(y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [25]:
# Try and change the shape of x, rather than y
tf.matmul(tf.reshape(x, shape=(2, 3)), y).numpy()

array([[ 58,  64],
       [139, 154]], dtype=int32)

In [27]:
# Can do the same with transpose
x, tf.transpose(x), tf.reshape(x, shape=(2, 3))

# transpose() just flips the tensor 90 degrees left.

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [28]:
# Try matmul with transpose rather than reshape
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

***The Dot Product***

Matrix mul is also referred to as the dot product.

You can perform matmul using:

-tf.matmul()

-tf.tensordot()

In [29]:
# perform the dot product on x and y (requires x and y to be tranposed)
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [30]:
# Perform matmul between x and y (transposed)
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [32]:
# Perform matmul between x and y (reshaped)
tf.matmul(x, tf.reshape(y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [35]:
# Check the values of y, reshaped y, and transposed y
print("Normal y:")
print(y, "\n") # "\n" means new line

print("y reshaped to (2, 3):")
print(tf.reshape(y, shape=(2, 3)))

print("y transposed:")
print(tf.transpose(y))

# Generally, you tranpose() rather than reshaping them

Normal y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Changing the datatype of a tensor

In [37]:
# Create a new tensor with default datatype (float32)
b = tf.constant([1.7, 7.4])
print(b.dtype)
c = tf.constant([7, 10])
c.dtype

<dtype: 'float32'>


tf.int32

In [40]:
# Change from float32 to float16 (reduced precision)
b = tf.cast(b, dtype=tf.float16)
d = tf.cast(b, dtype=tf.float16)
d, d.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [42]:
# Change from int32 to float32
e = tf.cast(c, dtype=tf.float32)
e.dtype, c.dtype

(tf.float32, tf.int32)

In [44]:
e_float16 = tf.cast(e, dtype=tf.float16)
e_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

Aggregating tensors

Condensing them from multiple values down to a smaller amount of values.

-Get min, max, mean, and sum of a tensor

In [46]:
# Get the absolute values
d = tf.constant([-7, -10])
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [49]:
# Create a random tensor with values between 0 and 100 of size 50
e = tf.constant(np.random.randint(0, 100, size=50))
e, tf.size(e), e.shape, e.ndim

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([43, 43, 54, 47, 50, 10, 50, 63, 28, 73, 19, 86, 58, 78, 97, 15, 60,
        69, 51, 72, 98, 11, 52, 35, 46, 61, 42, 36,  9, 57, 65, 75, 99, 81,
        32, 23, 26, 96, 18, 88, 18, 36,  9,  9, 81, 53, 38,  2, 31, 98])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 TensorShape([50]),
 1)

In [56]:
# Get min
print(tf.reduce_min(e))

#Get max
print(tf.reduce_max(e))

# Get the mean
print(tf.reduce_mean(e))

# Get sum
print(tf.reduce_sum(e))

# Get variance
print(tfp.stats.variance(e))

# Get stndv
print(tfp.stats.stddev(tf.cast(e, dtype=tf.float32))) # When you just do stddev(e), it says int32 
                                                      # cannot be used. HAS TO BE CASTED FIRST.

tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(99, shape=(), dtype=int64)
tf.Tensor(49, shape=(), dtype=int64)
tf.Tensor(2491, shape=(), dtype=int64)
tf.Tensor(753, shape=(), dtype=int64)
tf.Tensor(27.444263, shape=(), dtype=float32)


*** Find the positional maximum and min***

-If you had a tensor as the output and you wanted to find out where the max confidence is, you do this

In [59]:
# Create a new tensor for finding positional min and max
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [66]:
# Find the positional max
tf.argmax(f) # Returns the index of the cell with the largest value

# Find the max number
f[tf.argmax(f)]

# Find the max value of F
tf.reduce_max(f)

if f[tf.argmax(f)] == tf.reduce_max(f):
  print("R the same")
else: 
  print("Not the same")

R the same


In [67]:
# Find the positional min
tf.argmin(f)

# Find the min number
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

***Squeezing a tensor(removing all single dimensions)***

In [73]:
# Create a random tensor
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))

g_squeezed = tf.squeeze(g)
g, g_squeezed, g_squeezed.shape # Squeeze just gets rid of the extra brackets at the front

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>, <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0

***One-hot encoding tensor***

-inputs have to be numbers so one-hot encoding helps to encode those inputs(if they are not numbers)

In [74]:
# Create a list of indices
some_list = [0, 1, 2, 3] # Could be red, green, blue, purple

# One hot encode our list of indicies
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [75]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="dumplings", off_value="pat")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'dumplings', b'pat', b'pat', b'pat'],
       [b'pat', b'dumplings', b'pat', b'pat'],
       [b'pat', b'pat', b'dumplings', b'pat'],
       [b'pat', b'pat', b'pat', b'dumplings']], dtype=object)>

### Squaring, log, square root

In [76]:
# Create a new tensor
h = tf.range(1, 10) 
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [82]:
# Square
tf.square(h)

# Sqrt
tf.sqrt(tf.cast(h, dtype=tf.float16))

# Log
tf.math.log(tf.cast(h, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

In [87]:
# Create a tensor directly from a NumPy array
j = tf.constant(np.array([3., 7., 10.]))

# Convert out tensor back to a NumPy array
np.array(j), type(np.array(j))

# Can also do
j.numpy(), type(j.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [91]:
# The default types of each are slightly different
numpy_j = tf.constant(np.array([3., 7., 10]))
tensor_j = tf.constant([3., 7., 10.])

# Check the datatypes of each
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32, numpy.ndarray)

### Module 1